CREATE TABLE rotors
(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    rotor_name TEXT,
    wiring TEXT,
    date_introduced DATE,
    model TEXT
);

CREATE TABLE reflectors
(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    reflector_name TEXT NOT NULL,
    wiring TEXT NOT NULL

);



INSERT INTO reflectors (reflector_name, wiring)
VALUES
    ('Beta', 'LEYJVCNIXWPBQMDRTAKZGFUHOS'),
    ('Gamma','FSOKANUERHMBTIYCWLQPZXVGJD'),
    ('A','EJMZALYXVBWFCRQUONTSPIKHGD'),
    ('B','YRUHQSLDPXNGOKMIEBFZCWVJAT'),
    ('C','FVPJIAOYEDRZXWGCTKUQSBNMHL'),
    ('B Thin','ENKQAUYWJICOPBLMDXZVFTHRGS'),
    ('C Thin','RDOBJNTKVEHMLFCWZAXGYIPSUQ'),
    ('ETW','ABCDEFGHIJKLMNOPQRSTUVWXYZ')
;

INSERT INTO rotors (rotor_name, wiring, date_introduced, model)
VALUES
    ('IC','DMTWSILRUYQNKFEJCAZBPGXOHV',1924,'Commercial Enigma'),
    ('IIC','HQZGPJTMOBLNCIFDYAWVEUSRKX',1924,'Commercial Enigma'),
    ('IIIC','UQNTLSZFMREHDPXKIBVYGJCWOA',1924,'Commercial Enigma')
;

INSERT INTO rotors (rotor_name, wiring, date_introduced, model)
VALUES
    ('I','JGDQOXUSCAMIFRVTPNEWKBLZYH',1941,'German Railway'),
    ('II','NTZPSFBOKMWRCJDIVLAEYUXHGQ',1941,'German Railway'),
    ('III','JVIUBHTCDYAKEQZPOSGXNRMWFL',1941,'German Railway'),
    ('UKW','QYHOGNECVPUZTFDJAXWMKISRBL',1941,'German Railway'),
    ('ETW','QWERTZUIOASDFGHJKPYXCVBNML',1941,'German Railway')
;

INSERT INTO rotors (rotor_name, wiring, date_introduced, model)
VALUES
    ('I-K','PEZUOHXSCVFMTBGLRINQJWAYDK',1939,'Swiss K'),
    ('II-K','ZOUESYDKFWPCIQXHMVBLGNJRAT',1939,'Swiss K'),
    ('III-K','EHRVXGAOBQUSIMZFLYNWKTPDJC',1939,'Swiss K'),
    ('UKW-K','IMETCGFRAYSQBZXWLHKDVUPOJN',1939,'Swiss K'),
    ('ETW-K','QWERTZUIOASDFGHJKPYXCVBNML',1939,'Swiss K')
;

INSERT INTO rotors (rotor_name, wiring, date_introduced, model)
VALUES
    ('I','EKMFLGDQVZNTOWYHXUSPAIBRCJ',1939,'M3 & M4'),
    ('II','AJDKSIRUXBLHWTMCQGZNPYFVOE',1939,'M3 & M4'),
    ('III','BDFHJLCPRTXVZNYEIWGAKMUSQO',1939,'M3 & M4'),
    ('IV','ESOVPZJAYQUIRHXLNFTGKDCMWB',1939,'M3 & M4'),
    ('V','VZBRGITYUPSDNHLXAWMJQOFECK',1939,'M3 & M4'),
    ('VI','JPGVOUMFYQBENHZRDKASXLICTW',1939,'M3 & M4'),
    ('VII','NZJHGRCXMYSWBOUFAIVLPEKQDT',1939,'M3 & M4'),
    ('VIII','FKQHTLXOCBJSPDZRAMEWNIUYGV',1939,'M3 & M4')
;
